park-manager/park-manager

- .dancer.yml
- .dancer/Configurator/ComposerConfigurator.php
- .dancer/Configurator/HttpActionConfigurator.php
- .dancer/Configurator/ModuleConfigurator.php
- .dancer/Generator/HttpActionGenerator.php
- .dancer/Generator/ModuleBundleGenerator.php
- .dancer/Generator/ModuleGenerator.php
- .dancer/base.yml
- .dancer/templates/Testing/phpunit.xml.twig
- .dancer/templates/http/action.php.twig
- .dancer/templates/http/action_form.php.twig
- .dancer/templates/http/action_list.php.twig
- .dancer/templates/readme.md.twig
- composer.json
| Branch?       | master 
| Fixed tickets |  
> Add SkeletonDancer templates and configuration

- .php_cs.dist
- .travis.yml
- Makefile
- composer.json
- phpspec.yml.dist
- src/Common/Domain/ConstraintFailed.php
- src/Common/Domain/EmailAddress.php
- src/Common/Domain/HoldsIdentity.php
- src/Common/Tests/Domain/HoldsIdentityTest.php
- src/Common/spec/Domain/EmailAddressSpec.php
> [Common] Add some Domain ValueObjects

- .php_cs.dist
- .travis.yml
- composer.json
- phpstan.neon
- phpunit.xml.dist
> Add phpstan to travis jobs

- .travis.yml
- composer.lock
> Trying to Fix travis failure

- .circleci/config.yml
- .php_cs.dist
- src/Bundle/UserBundle/Form/Handler/RequestPasswordResetFormHandler.php
- src/Bundle/UserBundle/Resources/config/services/form.xml
- src/Component/Core/Tests/Model/Handler/RegisterUserHandlerTest.php
- src/Component/Model/Test/DomainMessageAssertion.php
- src/Component/Model/Test/EventsRecordingAggregateRootAssertionTrait.php
- src/Component/Security/Tests/Token/SplitTokenValueHolderTest.php
- src/Component/Security/Token/SplitToken.php
- src/Component/User/Model/Command/ChangeUserPassword.php
- src/Component/User/Model/Command/ConfirmUserPasswordReset.php
- src/Component/User/Model/User.php
- src/Component/User/Security/Argon2iPasswordEncoder.php
- src/Component/User/Tests/Model/Handler/ConfirmEmailAddressChangeHandlerTest.php
- src/Component/User/Tests/Model/Handler/ConfirmUserPasswordResetHandlerTest.php
- src/Component/User/Tests/Model/UserTest.php
- src/Component/User/Tests/Security/Argon2iPasswordEncoderTest.php
> Correct CS

- phpstan.neon
- src/Component/WebUI/.gitattributes
- src/Component/WebUI/.gitignore
- src/Component/WebUI/BaseConfirmationHandler.php
- src/Component/WebUI/CHANGELOG.md
- src/Component/WebUI/CheckedConfirmationHandler.php
- src/Component/WebUI/ConfirmationHandler.php
- src/Component/WebUI/LICENSE
- src/Component/WebUI/README.md
- src/Component/WebUI/Tests/CheckedConfirmationHandlerTest.php
- src/Component/WebUI/Tests/ConfirmationHandlerTest.php
- src/Component/WebUI/Tests/templates/checked_confirm.html.twig
- src/Component/WebUI/Tests/templates/confirm.html.twig
- src/Component/WebUI/composer.json
| Doc PR        | 
The WebUI provides a collection of classes and services for (classic) WebUIs, with this pull request this component currently only contains the ConfirmationHandler. And will in time grow into a powerful component.
> [WebUI] Initialize component

- src/Bundle/UserBundle/Tests/Action/ConfirmPasswordResetActionTestCase.php
> Clean-up tests

- .circleci/config.yml
- .env.dist
- Makefile
| Fixed tickets | N/A
| Doc PR        | N/A
> Fix Makefile

- src/Module/Webhosting/Infrastructure/Symfony/DependencyInjection/Compiler/CommandToCapabilitiesGuardPass.php
- src/Module/Webhosting/Infrastructure/Symfony/DependencyInjection/Configuration.php
- src/Module/Webhosting/Infrastructure/Symfony/DependencyInjection/DependencyExtension.php
- src/Module/Webhosting/Infrastructure/Symfony/DependencyInjection/services/core.php
- src/Module/Webhosting/Model/Account/AccountIdAwareCommand.php
- src/Module/Webhosting/Model/Package/CapabilitiesGuard.php
- src/Module/Webhosting/Model/Package/CapabilityGuard.php
- src/Module/Webhosting/Model/Package/CommandSubscribingCapability.php
- src/Module/Webhosting/ParkManagerWebhostingBundle.php
- src/Module/Webhosting/Service/Package/AccountCapabilitiesGuard.php
- src/Module/Webhosting/Service/Package/CommandToCapabilitiesGuard.php
- src/Module/Webhosting/Tests/Fixtures/Capability/MailboxCountCount.php
- src/Module/Webhosting/Tests/Fixtures/Infrastructure/Package/Capability/MonthlyTrafficQuotaGuard.php
- src/Module/Webhosting/Tests/Fixtures/Infrastructure/Package/Capability/MonthlyTrafficQuotaGuard2.php
- src/Module/Webhosting/Tests/Fixtures/Model/Mailbox/CreateMailbox.php
- src/Module/Webhosting/Tests/Fixtures/Model/Mailbox/RemoveMailbox.php
- src/Module/Webhosting/Tests/Fixtures/Model/Package/Command/CreatePackage.php
- src/Module/Webhosting/Tests/Infrastructure/Symfony/DependencyInjection/Compiler/CommandToCapabilitiesGuardPassTest.php
- src/Module/Webhosting/Tests/Infrastructure/Symfony/DependencyInjection/ConfigurationTest.php
- src/Module/Webhosting/Tests/Service/Package/AccountCapabilitiesGuardTest.php
- src/Module/Webhosting/Tests/Service/Package/CommandToCapabilitiesGuardTest.php
> [Webhosting] Add CommandToCapabilitiesGuard

- .circleci/config.yml
- phpstan.neon
- src/Bridge/Doctrine/Type/ArrayCollectionType.php
- src/Bundle/CoreBundle/DependencyInjection/DependencyExtension.php
- src/Bundle/CoreBundle/Resources/config/services/administrator.php
- src/Bundle/UserBundle/Form/Type/ChangePasswordType.php
- src/Bundle/UserBundle/Form/Type/ConfirmPasswordResetType.php
- src/Bundle/UserBundle/Security/FormAuthenticator.php
- src/Component/Security/Token/SplitToken.php
- src/Component/Security/Token/SplitTokenValueHolder.php
- src/Component/User/Canonicalizer/Canonicalizer.php
- src/Component/User/Canonicalizer/SimpleEmailCanonicalizer.php
- src/Component/User/Model/User.php
- src/Component/User/Tests/Security/SecurityUserTest.php
- src/Module/Webhosting/Infrastructure/Doctrine/Type/WebhostingCapabilitiesType.php
- src/Module/Webhosting/Infrastructure/Symfony/DependencyInjection/DependencyExtension.php
- src/Module/Webhosting/Infrastructure/Symfony/DependencyInjection/services/core.php
| Branch?       | master 
| BC breaks?    | yes (stricter interfaces)
> Phpstan errors

- src/Bundle/CoreBundle/Cli/Command/RegisterAdministratorCommand.php
- src/Bundle/CoreBundle/ParkManagerCoreBundle.php
- src/Bundle/CoreBundle/Resources/config/services/administrator.php
- src/Bundle/UserBundle/Resources/config/services/security.xml
| Doc PR        | 
Register the RegisterAdministratorCommand as lazy-loaded service.
> [CoreBundle] Lazy RegisterAdministratorComman

- .travis.yml
- Makefile
- docker-compose.yaml
- docker/Dockerfile
- docker/Dockerfile-qa
- phpunit.xml.dist
> Attempt to use Travis with Docker

- composer.json
- src/Bridge/ServiceBus/DependencyInjection/Configurator/MiddlewaresConfigurator.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Configurator/MiddlewaresConfiguratorTest.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Fixture/AdvancedSpyMiddlewareConfigurator.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Fixture/SpyMiddlewareConfigurator.php
Fixed wrong namespace for Middleware configurators, and fixed wrong expectation for Middleware Configurator class-name.
> [ServiceBus] Fix Middleware configuring

- src/Bridge/ServiceBus/DependencyInjection/Compiler/DomainEventsEmitterPass.php
- src/Bridge/ServiceBus/DependencyInjection/Compiler/TracingDomainEventsEmitterPass.php
- src/Bridge/ServiceBus/DependencyInjection/Configurator/HandlersConfigurator.php
- src/Bridge/ServiceBus/DependencyInjection/Configurator/Middleware/DomainEventsMiddlewareConfigurator.php
- src/Bridge/ServiceBus/DependencyInjection/Configurator/MiddlewaresConfigurator.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Compiler/DomainEventsEmitterPassTest.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Compiler/TracingDomainEventsEmitterPassTest.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Configurator/HandlersConfiguratorTest.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Configurator/Middleware/DomainEventsMiddlewareConfiguratorTest.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Fixture/EventListener/RegisterAdminSubscriber.php
- src/Bridge/ServiceBus/Tests/DependencyInjection/Fixture/EventListener/RegisterUserListener.php
- src/Bundle/ServiceBusBundle/DependecyInjection/DependencyExtension.php
- src/Bundle/ServiceBusBundle/ParkManagerServiceBusBundleBundle.php
- src/Component/Model/DomainEventsCollectionTrait.php
- src/Component/Model/Event/DomainEvent.php
- src/Component/Model/Event/EventEmitter.php
- src/Component/Model/Event/EventSubscriber.php
- src/Component/Model/Event/SymfonyEventEmitter.php
- src/Component/Model/EventsRecordingEntity.php
- src/Component/Model/composer.json
> [Model][ServiceBus] Add Domain EventEmitter

- composer.json
- config/bundles.php
- phpstan.neon
- src/Bridge/ServiceBus/DependencyInjection/Configurator/MiddlewaresConfigurator.php
- src/Bundle/ServiceBusPolicyGuardBundle/.gitattributes
- src/Bundle/ServiceBusPolicyGuardBundle/.gitignore
- src/Bundle/ServiceBusPolicyGuardBundle/CHANGELOG.md
- src/Bundle/ServiceBusPolicyGuardBundle/DependencyInjection/Compiler/PolicyGuardConfigurationPass.php
- src/Bundle/ServiceBusPolicyGuardBundle/DependencyInjection/MiddlewareConfigurator/PolicyGuardMiddlewareConfigurator.php
- src/Bundle/ServiceBusPolicyGuardBundle/DependencyInjection/PolicyConfigHolder.php
- src/Bundle/ServiceBusPolicyGuardBundle/ExpressionLanguage/ExpressionLanguage.php
- src/Bundle/ServiceBusPolicyGuardBundle/Guard/PolicyGuard.php
- src/Bundle/ServiceBusPolicyGuardBundle/LICENSE
- src/Bundle/ServiceBusPolicyGuardBundle/ParkManagerServiceBusPolicyGuardBundle.php
- src/Bundle/ServiceBusPolicyGuardBundle/README.md
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/DependencyInjection/Compiler/PolicyGuardConfigurationPassTest.php
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/DependencyInjection/DependencyExtensionTest.php
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/DependencyInjection/MiddlewareConfigurator/PolicyGuardMiddlewareConfiguratorTest.php
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/Fixtures/Deeper/MessageC.php
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/Fixtures/MessageA.php
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/Fixtures/MessageB.php
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/Fixtures/ServiceA.php
- src/Bundle/ServiceBusPolicyGuardBundle/Tests/Guard/PolicyManagerTest.php
- src/Bundle/ServiceBusPolicyGuardBundle/composer.json
> Introduce ServiceBusPolicyGuardBundle

- config/bundles.php
- src/Bridge/ServiceBus/DependencyInjection/Configurator/Middleware/MessageGuardMiddlewareConfigurator.php
- src/Bundle/ServiceBusBundle/ParkManagerServiceBusBundle.php
> [ServiceBus] Some minor fixes

- src/Bridge/ServiceBus/Tests/Fixtures/Command/CommandA.php
- src/Bridge/ServiceBus/Tests/Guard/ValidatorMiddlewareTest.php
- src/Bridge/ServiceBus/Validator/InvalidCommandException.php
- src/Bridge/ServiceBus/Validator/ValidatorMiddleware.php
| Bug fix?      | yes/no
Note: This validator was copied from the TacticianBundle, but I was unable to find the original author information. I accept a pull-request to fix this 👍
> [ServiceBus] Add ValidatorMiddleware

- .env.dist
- composer.json
- composer.lock
- config/bundles.php
- config/packages/park_manager.yml
- config/packages/security.yaml
- docker-compose.yaml
- src/Bundle/CoreBundle/DependencyInjection/Configuration.php
- src/Bundle/CoreBundle/DependencyInjection/DependencyExtension.php
- src/Kernel.php
- symfony.lock
> [Core] Fix AppSectioning configuration

- .env
- .travis.yml
- Makefile
- docker/Dockerfile
- docker/php/conf.d/park-manager.ini
- phpunit.xml.dist
Hopefully this will fix the build failures.
> Fix Travis build

- Makefile
| Deprecations? | yes/no 
Add targets for Twig, YAML and XML files.
> Ci linting improvements

- .github/.psalm-stubs/symfony-di-dsl.php
- Makefile
- config/packages/park_manager.yaml
- config/packages/security.yaml
- docker-compose.yaml
- psalm.xml
- src/Module/CoreModule/Application/Service/Finder/Shared/AuthenticationFinder.php
- src/Module/CoreModule/Infrastructure/Doctrine/Shared/DoctrineDbalAuthenticationFinder.php
- src/Module/CoreModule/Infrastructure/Resources/config/services.php
- src/Module/CoreModule/Infrastructure/Resources/config/services/security.php
- src/Module/CoreModule/Infrastructure/Resources/templates/admin/security/login.html.twig
- src/Module/CoreModule/Infrastructure/Resources/translations/messages.en.yml
- src/Module/CoreModule/Infrastructure/Security/UserProvider.php
- src/Module/CoreModule/Tests/Infrastructure/Doctrine/Shared/DoctrineDbalAuthenticationFinderTest.php
- src/Module/CoreModule/Tests/Infrastructure/Security/UserProviderTest.php
> Fix administrator login
